name: React App CI Pipeline

on:
  push:
    branches:
      - 'main'  # Trigger this pipeline for changes pushed to 'main' branch
  pull_request:
    branches:
      - 'main'  # Trigger this pipeline for PRs targeting 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest  # Environment to run the job

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Node.js 18 or higher
      - name: Set up Node.js 18 or greater
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'  # This will select Node.js 18 or the latest version available (18.x or greater)

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          npm install  # Install project dependencies from package.json

      # Step 4: Run tests (optional)
      - name: Run tests
        run: |
          npm test -- --watchAll=false  # Run tests (adjust if needed)

      # Step 5: Build the app
      - name: Build the app
        run: |
          npm run build  # Build the React app for production
