name: React App CI Pipeline

on:
  push:
    branches:
      - 'main'  # Trigger this pipeline for changes pushed to the 'main' branch
  pull_request:
    branches:
      - 'main'  # Trigger this pipeline for PRs targeting the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest  # Environment to run the job

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Node.js 18 or greater
      - name: Set up Node.js 18 or greater
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'  # This will select Node.js version 18 or the latest version available

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          npm install  # Install project dependencies from package.json
      # Step 4: Run Prettier formatting check
      - name: Run Prettier formatting check
        run: |
          npx prettier --check .  # Check code formatting using Prettier
        continue-on-error: false 
        
      # Step 5: Build the app
      - name: Build the app
        run: |
          npm run build  # Build the React app for production

      # Optional: Deploy the app (if needed)
      # - name: Deploy to Server
      #   run: |
      #     # Add your deployment steps here (e.g., upload to a server, or deploy to Netlify, Vercel, etc.)
